name: sushichain
description: Sushichain flutter crypto package
version: 0.0.1
author: Kingsley Hendrickse <kingsley@sushichain.io>
homepage: https://sushichain.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pointycastle: '^1.0.1'
  dartz: '^0.8.4'
  crypto: '^2.0.6'
  quiver_hashcode: '^2.0.0'
  convert: '^2.1.1'


dev_dependencies:
  flutter_test:
    sdk: flutter